### ISSUE TITLE
Group/factor via coordinates file names

### ISSUE THREAD

**Issue by raz1** [vbonhomme/Momocs#65]
Hi,
 
I am reading XY coordinates txt files (named: ACA1, ACA2, ACA3, ZCA1, ZCA2, ZCA3, ZCA4, XXA1, XXA2, XXA3, WA1, WA2, WA3, WA4) using the Out(coordinates, fac = data.frame).

As I wish to perform PCA, how can I group/factor them using the file names so I can plot them latter using colors and convex hulls.

Thanks.

**Comment by vbonhomme** [comment]
Hi,

Once you have your Out object declared with a data.frame for classifiers (named x in the example below) :
* you can calculate a PCA with : ```xp <- PCA(x)```
 *  then plot it with ```plot(xp, 1)``` for the first column, or ```plot(xp, "fac1")``` if the name of the colum you're interested in is "fac1".
* you can also try ```plot2``` which is a ggplot2 alternative temporary called plot2 that will replace ```plot``` at some point

**Comment by vbonhomme** [comment]
Overall, have a look to the examples in ?PCA and ?plot.PCA

**Comment by raz1** [comment]
My issue is with the "Once you have your Out object declared with a data.frame for classifiers (named x in the example below)". I do not understand the "data.frame for classifiers", can you elaborate more?

**Comment by vbonhomme** [comment]
if you have 40 individuals with classifiers such as : country, species, etc. you need to prepare a data.frame with 40 lines and 2 columns, with your labels. If your image names are named this way : France_sp1_1.jpg, France_sp2_1.jpg, etc. with an "_" separating every label, then you can use lf_structure. Have a look to ?lf_structure, ?Out, bot$fac, etc. First of all import all your txt files using import_txt
I'm preparing vignettes to explain all of it in the new version of Momocs.

**Comment by raz1** [comment]
I am not in this level of R so if you can give me an example using my image file names it will be great and very useful. When are you planning to release the vignettes?

**Comment by vbonhomme** [comment]
I'll release them when I'll have finished this version of Momocs which is
running since more than a year now.

1. Type: ```coo <- import_txt() ``` and select one of your files.
2. Then build your Out object : ```foo <- Out(coo)```
3. Then you can start doing things such a efourier, then PCA, then plotting
:
```
foo_f <- efourier(foo)
foo_p <- PCA(foo_f)
plot(foo_p)
```

But you also need so specify a $fac in your Out object. It can be based on
your filenames if you put an underscore, as explained in
```?lf_structure```.

Otherwise you send me by email your files and I will try to manage, but try
first and have a look to the helpfiles...






2015-02-18 16:16 GMT+01:00 raz1 <notifications@github.com>:

> I am not in this level of R so if you can give me an example using my
> image file names it will be great and very useful. When are you planning to
> release the vignettes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/65#issuecomment-74880592>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
